SELECT * FROM customer LIMIT 20;
--Q1.what is the total revenue generated by male vs. female customer?
SELECT gender,
       SUM("purchase_amount_(usd)") AS revenue
FROM customer
GROUP BY gender;
--Q2.which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, "purchase_amount_(usd)"
FROM customer
WHERE discount_applied = 'yes' AND "purchase_amount_(usd)" >= (SELECT AVG("purchase_amount_(usd)") FROM customer);
   
 --Q3.which are the top 5 products with the highest average review rating?
 SELECT item_purchased,AVG(review_rating)AS "Average product rating"
 FROM customer
 group by item_purchased
 order by avg(review_rating) desc
 limit 5;
 
--Q4.compare the average purchase amount between standard and express shipping.
SELECT shipping_type,
ROUND (AVG("purchase_amount_(usd)"),2)
FROM customer
WHERE shipping_type in ('Standard','Express')
GROUP BY shipping_type
--Q5.Do subscribed customers spend more?compare average spend and total revenue between subscribers and non subscribers.
SELECT subscription_status,
COUNT (customer_id)as total_customer,
ROUND (AVG( "purchase_amount_(usd)"),2)as avg_spend,
ROUND(SUM("purchase_amount_(usd)"),2)as total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend desc; which 5 products have the highest percentage o purchases
--Q6. which 5 products have the highest percentage of purchases with discounts applied.
SELECT item_purchased,
ROUND(100* sum(CASE WHEN discount_applied='yes' THEN 1 ELSE 0 END)/COUNT(*),2)as discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5; 
--Q7.segment customers into new ,returning, and loyal based on their total_number of previous purchases, and show the count of each segment.
WITH customer_type as(
SELECT customer_id,previous_purchases,
CASE
     WHEN previous_purchases = 1 THEN 'New'
	 WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	 ELSE 'Loyal'
	 END AS customer_segment
FROM customer
)

SELECT customer_segment,COUNT(*) as "Number of customers"
FROM customer_type
GROUP BY customer_segment
--Q8. what is the top 3 most purchased products within each category?
WITH item_counts as(
SELECT category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id)DESC) as item_rank
FROM customer
GROUP BY category,item_purchased
)

SELECT item_rank,category,item_purchased,total_orders
FROM item_counts
WHERE item_rank <= 3;

--Q9.Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
COUNT(customer_id) as repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status

--Q10.what is the revenue contribution of each age group?
SELECT age_group,
sum("purchase_amount_(usd)") as total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;